name: CCAddon
author: GamerDuck123
main: me.garrett.ccaddon.CCAddon
softdepend: [CrazyCrates]
depend: [PlaceholderAPI]
version: 1.0
description: >
             Display the items in your CrazyCrates Crates in style!
